NEGRO = (0, 0, 0)
BLANCO = (255, 255, 255)

BALDOSA_TAMANIO = 30
BALDOSA_NUMERO = 25
MARCADOR_ANCHURA = 32

ALTURA = BALDOSA_TAMANIO * BALDOSA_NUMERO
ANCHURA = BALDOSA_TAMANIO * BALDOSA_NUMERO + MARCADOR_ANCHURA

PUNTO_UNIDAD = 1

